a = input('Digite algo:')
print('O tipo primitivo de valor é', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print("É alphabetic?", a.isalpha())
print('É alfanumerico?', a.isalnum())
print('É esta em minusculas?', a.islower())
print('Esta em maísculas?', a.isupper())
print(' Esta capatizada?', a.istitle())
